---
AWSTemplateFormatVersion: "2010-09-09"
Description: Titan Agents DynamoDB Global Table

Parameters:
  enableReplica:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: "Enable DynamoDB Global Table Replica"
  kmsKeyAlias:
    Type: String
    Description: "KMS Key Alias for DynamoDB Encryption"

Conditions:
  enableReplica: !Equals [!Ref enableReplica, "true"]

Resources:
  dynamoDbGlobalTable:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      TableName: titan-agents-table
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: connection_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: connection_id
          AttributeType: S
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Replicas:
        - Region: us-east-1
          PointInTimeRecoverySpecification:
            PointInTimeRecoveryEnabled: true
          TableClass: STANDARD
          SSESpecification:
            KMSMasterKeyId: !Sub arn:aws:kms:us-east-1:${AWS::AccountId}:alias/${kmsKeyAlias}
        - !If
          - enableReplica
          - Region: us-east-2
            PointInTimeRecoverySpecification:
              PointInTimeRecoveryEnabled: true
            TableClass: STANDARD
            SSESpecification:
              KMSMasterKeyId: !Sub arn:aws:kms:us-east-2:${AWS::AccountId}:alias/${kmsKeyAlias}
          - !Ref "AWS::NoValue"
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
